
name: Bump version - wazuh-packages
on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create the PR'
        required: true
      version:
        description: 'Version to bump to. Format: x.x.x.'
        required: true
      revision:
        description: 'Revision to bump to. Default: 1'
        required: false
      date:
        description: 'Date to bump to. Format: m-d-Y. Default: today'
        required: false

jobs:
  bump-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.base_branch }}

      - name: Create branch for the bump
        run: |
            git config --global user.name "wazuhci"
            git config --global user.email "wazuhci@wazuh.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git branch bump-version-${{ github.event.inputs.version }}
            git push --set-upstream origin bump-version-${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: bump-version-${{ github.event.inputs.version }}

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.WAZUHCI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.WAZUHCI_GPG_PASSWORD }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set execution parameters
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=-v ${{ github.event.inputs.version }}" >> $GITHUB_ENV 
          fi
          if [ -n "${{ github.event.inputs.revision }}" ]; then
            echo "REVISION=-r ${{ github.event.inputs.revision }}" >> $GITHUB_ENV 
          fi
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo "DATE=-d ${{ github.event.inputs.date }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Bump version
        run: |
          python3 ./bump_version.py ${{ env.VERSION }} ${{ env.REVISION }} ${{ env.DATE }}
        shell: bash

      - name: "Commit changes and push"
        run: |
            export GPG_TTY=`tty`
            git add .
            git commit -m "Bump version to ${{ github.event.inputs.version }}"
            git push origin bump-version-${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
        shell: bash

      - name: "Create pull request"
        run: |
            gh pr create -B "${{ github.event.inputs.base_branch }}" -H "bump-version-${{ github.event.inputs.version }}" \
            --title 'Update branch ${{ github.event.inputs.base_branch }} to version ${{ github.event.inputs.version }}' \
            --body 'Pull request to bump branch ${{ github.event.inputs.base_branch }} to version ${{ github.event.inputs.version }}.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
